# Sales Records Analysis 
### Author: Malaika Tariq 
### Exercise 2.E Using functions for analyzing data 
This notebook analyzes a small sales dataset using Python functions. Each function takes the full dataset as its first argument.

In [1]:
sales_data = [
('Laptop', 'East', 1200.00),
('Phone', 'West', 850.00),
('Tablet', 'East', 400.00),
('Monitor', 'South', 650.00),
('Keyboard', 'West', 75.00),
('Laptop', 'South', 1150.00),
('Phone', 'East', 900.00),
('Tablet', 'West', 425.00),
('Monitor', 'East', 680.00),
('Keyboard', 'South', 80.00),
('Laptop', 'West', 1300.00),
('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region

In [2]:
def region_total(data, region):
    return sum(amt for _, r, amt in data if r == region)

print(region_total(sales_data, 'East')) 
print(region_total(sales_data, 'West')) 
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [4]:
def region_count(data, region):
     return sum(1 for _, r, amt in data if r == region)
    
print(region_count(sales_data, 'East')) 
print(region_count(sales_data, 'West')) 
print(region_count(sales_data, 'South'))

4
5
3


## Lab 3. Average sale amount by region

In [5]:
def region_average(data, region):
    count = region_count(data, region)
    if count == 0:
        return 0
    return region_total(data, region) / count 

print(region_average(sales_data, 'East')) 
print(region_average(sales_data, 'West')) 
print(region_average(sales_data, 'South'))
print(region_average(sales_data, 'North'))

795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount

In [7]:
def sales_above(data, threshold):
    return [record for record in data if record[2] > threshold]

above_500 = sales_above(sales_data, 500)
for record in above_500:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


In [8]:
# BONUS: 
def sales_below(data, threshold):
    return [record for record in data if record[2] < threshold]

below_500 = sales_above(sales_data, 500)
for record in below_500:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


## Lab 5. Top and bottom sale

In [10]:
def top_sale(data):
    return max(data, key=lambda s: s[2])

def bottom_sale(data):
    return min(data, key=lambda s: s[2])

print(top_sale(sales_data))
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The top sale was a Laptop in the West region for $1,300.00.

The bottom sale was a Keyboard in the West region for $75.00.

## Lab 6. Apply a discount

In [11]:
def apply_discount(data, discount_pct):
    return list(map(lambda s: (s[0], s[1], s[2] * (1 - discount_pct)), data))

# Test with 15% discount
print("Before discount:")
for record in sales_data[:3]:
    print(record)

discounted = apply_discount(sales_data, 0.15)
print("\nAfter 15% discount:")
for record in discounted[:3]:
    print(record)

Before discount:
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

After 15% discount:
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions

In [12]:
def unique_regions(data):
    return sorted(set(r for _, r, _ in data))

print(unique_regions(sales_data))

['East', 'South', 'West']


The unique regions() function is useful when you don't know what regions exist in a dataset.In a longer analysis program, you could use it to generate reports or charts for every region without hardcoding any region names, making the program flexible and resuable with different datasets.

## Lab 8. Region summary

In [20]:
def region_summary(data, region):
    region_data = [record for record in data if record[1] == region]
    total = region_total(data, region)
    count = region_count(data, region)
    avergae = region_average(data, region)
    top = top_sale(region_data) if region_data else None

    print(f"=== {region} Region ===")
    print(f"Records:      {count}")
    print(f"Total sale:   ${total:,.2f}")
    print(f"Average Sale: ${avergae:,.2f}")
    if top:
        print(f"Top Sale:     {top[0]} - ${top[2]:,.2f}")
    print()

region_summary(sales_data, 'East')
region_summary(sales_data, 'West')
region_summary(sales_data, 'South')

=== East Region ===
Records:      4
Total sale:   $3,180.00
Average Sale: $795.00
Top Sale:     Laptop - $1,200.00

=== West Region ===
Records:      5
Total sale:   $3,470.00
Average Sale: $694.00
Top Sale:     Laptop - $1,300.00

=== South Region ===
Records:      3
Total sale:   $1,880.00
Average Sale: $626.67
Top Sale:     Laptop - $1,150.00



## Lab 9. Full summary

In [21]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)

=== East Region ===
Records:      4
Total sale:   $3,180.00
Average Sale: $795.00
Top Sale:     Laptop - $1,200.00

=== South Region ===
Records:      3
Total sale:   $1,880.00
Average Sale: $626.67
Top Sale:     Laptop - $1,150.00

=== West Region ===
Records:      5
Total sale:   $3,470.00
Average Sale: $694.00
Top Sale:     Laptop - $1,300.00



# Summary

In this exercise I learned how to:
- Write resuable Python functions that accept a full dataset as their first argument.
- Use list comprehensions to filter datasets and return new lists.
- Use generator expressions inside sum() to filter and aggregate data in one line.
- Use map() with a lambda to transform every record without mutating the original data.
- Use max() and min() with a key= argument to find records by a specific field.
- Use set() to deduplicate values and sorted() to return them in order.
- Compose functions to avoid repeating logic.
- Build a full summary report.